name: blocExample
description: "News App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  card_swiper: ^3.0.1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  provider: ^6.1.2
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/no-image.jpg
    - assets/loading.gif
